baseURL = "https://nooblogaurus.com/"
languageCode = "en-us"
title = "Nooblogaurus"
theme = "PaperMod"
paginate = 5

canonifyURLs = true # Force l'utilisation de URLs absolues basées sur baseURL

[params.profileMode]
  enabled = true
  author = "Noobosaurus"
  title = "Welcome to Nooblogaurus! 🦖"
  subtitle = "A blog about cybersecurity, tools, cheat sheets, and more."
  showReadingTime = true
  showToc = true
  defaultTheme = "auto"
  favicon = "favicon.ico"
  imageUrl = "/assets/images/LOGO2.png"
  imageTitle = "Noobosaurus R3x"
  imageWidth = 120
  imageHeight = 120

[outputs]
home = ["HTML", "RSS", "JSON"]

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[[params.profileMode.buttons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/noobosaurus-r3x-683783231/"

[[params.profileMode.buttons]]
  name = "github"
  url = "https://github.com/noobosaurus-r3x"

[[params.profileMode.buttons]]
  name = "x"
  url = "https://x.com/NoobosaurusR3x"

[[params.profileMode.buttons]]
  name = "YouTube HacktBack"
  url = "https://www.youtube.com/@HacktBack"

[[params.profileMode.buttons]]
  name = "YouTube Noobosaurus"
  url = "https://www.youtube.com/@NoobosaurusR3x"

[params]
disableSearch = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 4
  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 3
  [[menu.main]]
    name = "Cheat Sheets"
    url = "/cheat-sheets/"
    weight = 2
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 5

